#!/bin/bash
#
# Upgrade IPCop
#

UPGRADEVERSION=1.9.20
PREVIOUSVERSION=1.9.19


msg() {
    /usr/bin/logger -t installpackage "$*"
    /bin/echo "$*"
}


# Verify architecture
MACHINE=`/usr/bin/perl -e "require '/usr/lib/ipcop/general-functions.pl';print \\$General::machine;"`
if [ "$MACHINE" != `/bin/cat ./ARCH` ]; then
    msg "Update for wrong architecture: `/bin/cat ./ARCH`! We are: $MACHINE. Aborting installation."
    exit 1
fi

# Verify version, note we also accept replaying an upgrade
CURRENTVERSION=`/usr/bin/perl -e "require '/usr/lib/ipcop/general-functions.pl';print \\$General::version;"`
if [ "$CURRENTVERSION" != "$PREVIOUSVERSION" -a "$CURRENTVERSION" != "$UPGRADEVERSION" ]; then
    msg "IPCop v$PREVIOUSVERSION or v$UPGRADEVERSION not running. Aborting installation."
    exit 1
fi

#####
#
# Add version specific handling *before* unpacking the patch here.
# For example stopping dnsmasq(required before update), squid, etc...
#
#####



#####
#
# End of version specific handling. Continue with universal stuff.
#
#####

FAILURE=0
/bin/tar -zxpf patch.tar.gz -C /
FAILURE=$?
if [ $FAILURE -ne 0 ]; then
    msg "Error extracting patch.tar.gz $1, need more free space on disk. Aborting."
    exit 4 # ERRORTAR
fi

# Modify or remove line below, depending on update
# Update bootloader config
/usr/local/sbin/updatekernel.pl --add 2.6.32-4 --keep 2.6.32-3 --remove 2.6.32-2

# Modify or remove line below, depending on update
# Create the new initramfs
/sbin/mkinitramfs --with-kernel=2.6.32-4 --with-firmware --many-modules --with-list=/etc/modules.initramfs

# Adjust the changed config files
# /usr/local/bin/upgrade.sh

# Remove old libraries (version specific)
/bin/rm -f /lib/libudev.so.0.9.1
/bin/rm -f /usr/lib/libfreetype.so.6.6.{1,2}
/bin/rm -f /usr/lib/libnet.so.1.5.0
/bin/rm -f /usr/lib/libpango*.3
/bin/rm -f /usr/lib/libapr-1.so.0.4.{2,4}
/bin/rm -f /usr/lib/libaprutil-1.so.0.3.{10,11}
/bin/rm -f /lib/libxtables.so.{5,6}
/bin/rm -f /lib/libxtables.so.{5,6}.0.0
/bin/rm -f /usr/lib/libdns.so.69.1.2
/bin/rm -f /lib/libcap.so.2.{20,21}
/bin/rm -f /usr/lib/libparted.so.0.0.1
/bin/rm -f /usr/lib/libpng15.so.15.0.0

# Replaced by xtables-multi
/bin/rm -f /sbin/ip6tables-multi
/bin/rm -f /sbin/iptables-multi

# For new shared libs. May not always be required, but makes sure we do not forget
/sbin/ldconfig

#####
#
# Add version specific handling *after* unpacking the patch here.
# For example restarting apache, squid, etc...
#
#####

# Fix SF 3000712 - Spike in traffic graphs after reboot
for INTERFACE in GREEN_1 BLUE_1 ORANGE_1 RED_1 ppp0; do
    if [ -f /var/log/rrd/${INTERFACE}.rrd ]; then
        /usr/bin/rrdtool tune /var/log/rrd/${INTERFACE}.rrd --data-source-type incoming:DERIVE
        /usr/bin/rrdtool tune /var/log/rrd/${INTERFACE}.rrd --data-source-type outgoing:DERIVE
    fi
done

# restart squid (helper checks whether squid is enabled)
/usr/local/bin/restartsquid

# Use new apache (restart pauses for 10 seconds, should be enough to complete upgrade)
/usr/local/bin/restarthttpd restart &

#####
#
# End of version specific handling. Continue with universal stuff.
#
#####

# Patch general-functions.pl
/bin/sed -i -e "s+^\(\$General::version\s*=\s*\).*+\1'$UPGRADEVERSION';+" /usr/lib/ipcop/general-functions.pl
# Patch /etc/issue
/bin/sed -i -e "s+$PREVIOUSVERSION+$UPGRADEVERSION+" /etc/issue

# Update menu
/usr/local/bin/updatemenu.pl

msg "$UPGRADEVERSION update installed."
