# This is the ipcop (CGI) language file with english text which are not yet inserted into the language
# database.
# Developers can insert new language texts here to have them on the ISO for testing until someone adds
# them to the database. If you add a language text to the database, please delete it here to avoid confusion.



%tr_new = (

######## Start Edit below ##########

#'access from red any is not allowed' => 'An Accept rule with source interface RED or Any is not allowed',
#'address grouping settings txt' => 'Address Grouping',
#'address settings txt' => 'Address settings',
#'adv firewall config' => 'Advanced BOT Config',
#'allow related, established' => 'Allow related, established',
#'allow related, established connections' => 'Allow related, established connections',
#'block out traff' => 'BlockOutTraffic',
#'block out traff is' => 'BlockOutTraffic is ',
#'blockouttraffic configuration' => 'BlockOutTraffic Configuration',
#'common firewall rule' => 'Common Firewall Rule',
#'connection state' => 'Connection state',
#'dhcp server disabled on blue interface' => 'DHCP server disabled on BLUE interface',
#'dhcp server enabled on blue interface' => 'DHCP server enabled on BLUE interface',
#'disable bot' => 'Disable BOT',
#'disable bot before edit settings' => 'Disable BlockOutTraffic before edit settings.',
#'disabledtitle' => 'Disabled',
#'enable bot' => 'Enable BOT',
#'error destination address in more secure network' => 'You can\'t create a rule with destination address in a more secure network (e.g. from Blue -&gt; Green Network)',
#'fw blue' => 'Blue',
#'fw green' => 'Green',
#'fw green vpn' => 'Green / VPN',
#'fw orange' => 'Orange',
#'fw red' => 'Red',
#'https port bad' => 'Invalid HTTPS port',
#'https port default 445' => 'HTTPS Port (Default is 445)',
#'https port' => 'HTTPS Port',
#'iface color long' => 'Interface color',
#'interface colorlevel blue' => 'All blue, orange, red interfaces',
#'interface colorlevel green' => 'All green, VPN, blue, orange, red interfaces',
#'interface colorlevel orange' => 'All orange, red interfaces',
#'interface colorlevel red' => 'All red interfaces',
#'interfaces settings txt' => 'Interfaces settings',
#'invalid iface color' => 'Invalid interface color',
#'invalid src port' => 'Invalid Source port',
#'ipcop access only from green and blue' => 'IPCop access is only allowed from Green and Blue!',
#'new rule' => 'New Rule',
# 'notes' => 'Notes',
# 'ntp after boot' => 'Synchronize Time after Boot',
#'service grouping settings txt' => 'Service Grouping',
#'services settings txt' => 'Services settings',
#'shaping add options' => 'Add service',
# 'vpn ca configuration' => 'Certificate Authorities configuration',


### Net-Traffic texts (Currently unused in GUI)
#'traffic page' => 'Utilisation',
#'trafficgreen' => 'Internal net',
# 'trafficred' => 'Internet',
#'trafficorange' => 'DMZ',
#'trafficblue' => 'WLAN',
#'net-traffic disabled' => 'Net-Traffic disabled',
#'net-traffic enabled' => 'Net-Traffic enabled',
#'disable net-traffic' => 'Disable Net-Traffic',
#'enable net-traffic' => 'Enable Net-Traffic',
#'shutdown red at traffic 1' => 'Shutdown Red when',
#'shutdown red at traffic 2' => ' of the monthly volume is reached',
#'limit per dial' => 'Limit per dial',
#'limit per month' => 'Limit per month',
#'dial volume' => 'Volume per dial (MByte)',
#'email adr' => 'Email address',



### bunch from OpenVPN  (Currently unused)
#'connect' => 'OVPN Start / Connect',
#'disconnect' => 'OVPN Stop / Disconnect',
#'add new ovpn' => 'OpenVPN Settings:',
#'Remote IP' => 'Remote IP / Hostname (DynDNS):',
#'comment' => 'Description:',
#'alt ovpn' => 'OpenVPN',
#'ovpn' => 'OpenVPN',
#'ovpn log' => 'OVPN-Log',
#'ovpn config' => 'OVPN-Config',
#'ovpnstatus log' => 'OVPN-Status-Log',
#'ovpnsys log' => 'OVPN-System-Log',
#'current ovpn' => 'Active OVPN-Connection:',
#'Local VPN IP' => 'Internal Network (GREEN):',
#'Remote VPN IP' => 'VPN Subnet (e.g. 10.0.10.0/255.255.255.0):',
#'Ping'=> 'Ping :',
#'optional data'=> '3. Optional Settings:',
#'requested data' => '1. Connection Settings:',
#'Resolv'=> 'Resolv-Retry:',
#'Verbose'=> 'Verbose:',
#'choose config' => 'Choose Config',
#'generate' => 'Generate Root/Host Zertifikate',
#'test' => 'test',
#'ovpn dl' => 'OVPN-Config Download',
#'key stuff' => '2. Keys and Certificates',
#'status ovpn' => '4. OpenVPN Status / Configuration',
#'manage ovpn' => '5. Tunnel Management:',
#'genkey' => 'Generate PSK',
#'exportkey' => 'Export PSK',
#'importkey' => 'Import PSK',
#'OpenVPN' => 'OpenVPN',
#'o-yes' => 'Activ',
#'o-no' => 'Inactiv',
#'error external access' => 'Could not open /var/ipcop/xtaccess/config (external acccess could not be granted)!',
#'error config' => 'Could not open /var/ipcop/ovpn/config/ZERINA.ovpn !',
#'hint' => 'Hint:',
#'debugme' => 'Not yet implemented',
#'Act as' => 'Act as:',
#'openvpn client' => 'OpenVPN Client',
#'gen static key' => 'Generate a static Key',
#'upload static key' => 'Upload a static Key',
#'external access rule changed' => 'External access rule changed; restarting access controller',
#'openvpn server status', => 'Current OpenVPN Server Status',
#'invalid input for dhcp dns' => 'Invalid input for DHCP DNS',
#'invalid input for dhcp wins' => 'Invalid input for DHCP WINS',
#'ovpn_processprio' => 'Process priority',
#'ovpn_fastio' => 'Fast-IO',
#'ovpn_mtudisc' => 'MTU-Discovery',
#'ovpn_mssfix' => 'MSSFIX Size',
#'ovpn_fragment' => 'Fragmentsize',
#'ovpn_processprioEH' => 'Extremely high',
#'ovpn_processprioVH' => 'Very high',
#'ovpn_processprioH' => 'High',
#'ovpn_processprioEN' => 'More highly than normal',
#'ovpn_processprioN' => 'Normal',
#'ovpn_processprioLN' => 'More deeply than normal',
#'ovpn_processprioD' => 'Deeply',
#'ovpn_processprioVD' => 'Very deeply',
#'ovpn_processprioED' => 'Extremely deeply',
#'server reserved' => 'The connection name server is reserved and not allowed',
#'add-route' => 'Additional push route',
#'subnet' => 'Subnet',
#'route subnet is invalid' => 'Additional push route subnet is invalid',
#'radius settings' => 'Radius settings',
#'radius nas settings' => 'Radius NAS settings',
#'radius nas-identifier' => 'NAS-Identifier',
#'radius service-type' => 'Service-Type',
#'radius framed-protocol' => 'Framed-Protocol',
#'radius nas-port-type' => 'NAS-Port-Type',
#'radius nas-ip-address' => 'NAS-IP-Address',
#'save-radius-settings' => 'Save Radius settings',
#'broken pipe' => 'Broken pipe',
#'cant start openssl' => 'Can\'t start OpenSSL',

# from advproxy for proxy.cgi (Currently unused)
#'no cre groups' => 'There are no access groups available',
#'cre disabled' => 'The management interface has been disabled by the Administrator',
#'save and restart' => 'Save and restart',
#'LDAP auth' => 'LDAP authentication',
#'NTLM auth' => 'Windows NT/2003 authentication',
#'chgwebpwd change web password' => 'C h a n g e &nbsp; w e b &nbsp; a c c e s s &nbsp; p a s s w o r d',
#'chgwebpwd username' => 'Username',
#'chgwebpwd old password' => 'Current password',
#'chgwebpwd new password' => 'New password',
#'chgwebpwd new password confirm' => 'New password (confirm)',
#'chgwebpwd change password' => 'Change password',
#'errmsg no password' => 'Password can not be empty',
#'errmsg invalid user' => 'Username does not exist',
#'errmsg password incorrect' => 'Password incorrect',
#'errmsg change fail' => 'Password could not be changed',
#'errmsg change success'  => 'Password for web access sucessfully changed',
#'chgwebpwd SUCCESS' => 'S U C C E S S :',
#'chgwebpwd ERROR' => 'E R R O R :',

#~ 'urlfilter assigned quota users' => 'Assigned users (one per line)',
#~ 'urlfilter assigned users' => 'Assigned users',
#~ 'urlfilter automatic blacklist update' => 'Automatic blacklist update',
#~ 'urlfilter automatic update schedule' => 'Automatic update schedule',
#~ 'err create backup file' => 'Unable to create backup file',
#~ 'urlfilter backup settings' => 'Backup URL filter settings',
#~ 'create backup file' => 'Create backup file',
#~ 'urlfilter blacklist age 1' => 'Last successful blacklist update was',
#~ 'urlfilter blacklist age 2' => 'days ago',
#~ 'blacklist category name' => 'Blacklist category name',
#~ 'urlfilter blacklist editor info' => 'Create and edit your own blacklist files',
#~ 'urlfilter blacklist editor' => 'Blacklist editor',
#~ 'blacklist name' => 'Blacklist name',
#~ 'urlfilter blacklist update' => 'Blacklist update',
#~ 'urlfilter block settings' => 'Block page settings',
#~ 'errmsg blacklist empty' => 'Blacklist is empty',
#~ 'errmsg category name error' => 'Blacklist category name required',
#~ 'urlfilter current files' => 'Current files in local repository',
#~ 'domains' => 'Domains (one per line)',
#~ 'dont restart urlfilter' => 'Do not restart URL filter',
#~ 'errmsg at least one category must be selected' => 'There must be at least one category selected',
#~ 'edit domains urls expressions' => 'Edit domains, URLs and expressions',
#~ 'urlfilter empty repository' => 'Local file repository is empty',
#~ 'enable automatic update' => 'Enable automatic update',
#~ 'urlfilter enable custom expression list' => 'Enable custom expression list',
#~ 'urlfilter enable full backup' => 'Include complete blacklist',
#~ 'urlfilter enable rewrite rules' => 'Enable local file redirection',
#~ 'export blacklist' => 'Export blacklist',
#~ 'err create export file' => 'Unable to create export file',
#~ 'expressions' => 'Expressions (one per line)',
#~ 'urlfilter filter settings' => 'URL filter settings',
#~ 'import blacklist' => 'Import blacklist',
#~ 'blacklist import text' => 'To import a previously saved blacklist editor file upload the .tar.gz file below',
#~ 'install blacklist' => 'Install blacklist',
#~ 'install blacklist information' => 'The new blacklist will be automatically compiled to prebuilt databases. Depending on the size of the blacklist, this may take several minutes.',
#~ 'errmsg invalid blacklist content' => 'File is not a squidGuard compatible blacklist',
#~ 'errmsg invalid import file' => 'File is not a valid URL filter blacklist editor file',
#~ 'urlfilter invalid ip or mask error' => 'Invalid IP address or network mask',
#~ 'errmsg invalid restore file' => 'File is not a valid URL filter backup file',
#~ 'urlfilter invalid user error' => 'Invalid username',
#~ 'load blacklist' => 'Load blacklist',
#~ 'urlfilter local file redirection' => 'Local file redirection',
#~ 'urlfilter log summary' => 'Total number of URL filter hits for',
#~ 'urlfilter manage local file repository' => 'Manage local file repository',
#~ 'urlfilter manage repository' => 'Manage repository',
#~ 'urlfilter network access control' => 'Network based access control',
#~ 'quota restart message' => 'Note: The counters will be reset for all users when restarting the URL filter',
#~ 'errmsg quota time' => 'Invalid value for time quota',
#~ 'errmsg quota user' => 'At least one username is required',
#~ 'urlfilter remove file' => 'Remove file from repository',
#~ 'urlfilter repository information' => 'Download requests for these files will be redirected from the original source to the local file repository.',
#~ 'urlfilter reset' => 'Reset',
#~ 'urlfilter restart message' => 'The URL filter must be restarted to activate the changed rules',
#~ 'urlfilter restart notification' => 'Activate changed rules',
#~ 'restart urlfilter' => 'Restart URL filter',
#~ 'restore results' => 'Restore results',
#~ 'urlfilter restore settings' => 'Restore URL filter settings',
#~ 'urlfilter restore success' => 'URL filter configuration has been restored. The URL filter must be restarted to activate the new settings.',
#~ 'urlfilter restore text' => 'To restore a previously saved configuration upload the .tar.gz backup file below',
#~ 'import backup file' => 'Import backup file',
#~ 'urlfilter safesearch' => 'Enable SafeSearch',
#~ 'urlfilter save and restart' => 'Save and restart',
#~ 'urlfilter save schedule' => 'Save update settings',
#~ 'select blacklist' => 'Select existing blacklist',
#~ 'urlfilter select multi' => 'Press Ctrl key to select multiple categories',
#~ 'urlfilter select source' => 'Select download source',
#~ 'urlfilter set user quota' => 'Set user quota',
#~ 'urlfilter show dnserror' => 'Use \"DNS Error\" to block URLs',
#~ 'errmsg src empty' => 'Source cannot be empty',
#~ 'errmsg extract tar' => 'Could not extract files from tar archive',
#~ 'urlfilter update information' => 'There is an updated version available for download. Visit <a href=\"http://www.urlfilter.net\" target=\"_blank\">http://www.urlfilter.net</a> for more information.',
#~ 'urlfilter update notification' => 'Update notification!',
#~ 'blacklist update results' => 'Blacklist update results',
#~ 'urlfilter upload background' => 'Upload image',
#~ 'urlfilter upload blacklist' => 'Upload blacklist',
#~ 'urlfilter upload file information 2' => 'The URL filter needs to be restarted to activate changes to the repository.',
#~ 'urlfilter upload file text' => 'To add a file to the local repository upload the file below',
#~ 'urlfilter upload information' => 'The new blacklist will be automatically compiled to prebuilt databases. Depending on the size of the blacklist, this may take several minutes. Please wait for this task to be finished before restarting the URL filter.',
#~ 'blacklist upload success' => 'Blacklist upload successfully completed.',
#~ 'urlfilter upload text' => 'To install an updated blacklist upload the .tar.gz file below',
#~ 'urlfilter urlfilter blacklist editor' => 'URL filter blacklist editor',
#~ 'urls' => 'URLs (one per line)',
#~ 'urlfilter user time quota' => 'Time quota (in minutes)',
#~ 'errmsg web proxy service required' => 'Web proxy service must be enabled to use URL filter',
#~ 'errmsg weekday' => 'There must be at least one day selected',
#~ 'errmsg wrong filetype' => 'File has not the extension .tar.gz',
######## Stop Edit above ##########



);

# always return true
1;
