#!/bin/bash
#
# Upgrade IPCop
#

UPGRADEVERSION=1.9.19
PREVIOUSVERSION=1.9.18


msg() {
    /usr/bin/logger -t installpackage "$*"
    /bin/echo "$*"
}


# Verify architecture
MACHINE=`/usr/bin/perl -e "require '/usr/lib/ipcop/general-functions.pl';print \\$General::machine;"`
if [ "$MACHINE" != `/bin/cat ./ARCH` ]; then
    msg "Update for wrong architecture: `/bin/cat ./ARCH`! We are: $MACHINE. Aborting installation."
    exit 1
fi

# Verify version, note we also accept replaying an upgrade
CURRENTVERSION=`/usr/bin/perl -e "require '/usr/lib/ipcop/general-functions.pl';print \\$General::version;"`
if [ "$CURRENTVERSION" != "$PREVIOUSVERSION" -a "$CURRENTVERSION" != "$UPGRADEVERSION" ]; then
    msg "IPCop v$PREVIOUSVERSION or v$UPGRADEVERSION not running. Aborting installation."
    exit 1
fi

#####
#
# Add version specific handling *before* unpacking the patch here.
# For example stopping dnsmasq(required before update), squid, etc...
#
#####



#####
#
# End of version specific handling. Continue with universal stuff.
#
#####

FAILURE=0
/bin/tar -zxpf patch.tar.gz -C /
FAILURE=$?
if [ $FAILURE -ne 0 ]; then
    msg "Error extracting patch.tar.gz $1, need more free space on disk. Aborting."
    exit 4 # ERRORTAR
fi

# Update bootloader config
/usr/local/sbin/updatekernel.pl --add 2.6.32-3 --keep 2.6.32-2 --remove 2.6.32-1

# Create the new initramfs
/sbin/mkinitramfs --with-kernel=2.6.32-3 --with-firmware --many-modules --with-list=/etc/modules.initramfs

# Adjust the changed config files
# /usr/local/bin/upgrade.sh

# Remove old libraries (version specific)
/bin/rm -f /lib/libhistory.so.6
/bin/rm -f /lib/libhistory.so.6.1
/bin/rm -f /lib/libreadline.so.6
/bin/rm -f /lib/libreadline.so.6.1
/bin/rm -f /lib/ld-2.11.2.so
/bin/rm -f /lib/libc-2.11.2.so
/bin/rm -f /lib/libcidn-2.11.2.so
/bin/rm -f /lib/libcrypt-2.11.2.so
/bin/rm -f /lib/libdl-2.11.2.so
/bin/rm -f /lib/libm-2.11.2.so
/bin/rm -f /lib/libnsl-2.11.2.so
/bin/rm -f /lib/libnss_compat-2.11.2.so
/bin/rm -f /lib/libnss_dns-2.11.2.so
/bin/rm -f /lib/libnss_files-2.11.2.so
/bin/rm -f /lib/libpthread-2.11.2.so
/bin/rm -f /lib/libresolv-2.11.2.so
/bin/rm -f /lib/librt-2.11.2.so
/bin/rm -f /lib/libutil-2.11.2.so
/bin/rm -f /usr/lib/rsyslog/immark.so
/bin/rm -f /usr/lib/rsyslog/imtcp.so
/bin/rm -f /usr/lib/rsyslog/imudp.so
/bin/rm -f /usr/lib/rsyslog/lmregexp.so
/bin/rm -f /usr/lib/rsyslog/lmstrmsrv.so
/bin/rm -f /usr/lib/rsyslog/lmtcpsrv.so
/bin/rm -f /usr/lib/rsyslog/lmzlibw.so
/bin/rm -f /usr/lib/rsyslog/omruleset.so
/bin/rm -f /usr/lib/rsyslog/omtesting.so

# For new shared libs. May not always be required, but makes sure we do not forget
/sbin/ldconfig

#####
#
# Add version specific handling *after* unpacking the patch here.
# For example restarting apache, squid, etc...
#
#####

# Restart rsyslogd to activate new version
/usr/local/bin/restartsyslogd

# Restart ntp daemon
if [ -e /var/run/ntpd.pid ]; then
    /usr/local/bin/restartntpd
fi

#####
#
# End of version specific handling. Continue with universal stuff.
#
#####

# Patch general-functions.pl
/bin/sed -i -e "s+^\(\$General::version\s*=\s*\).*+\1'$UPGRADEVERSION';+" /usr/lib/ipcop/general-functions.pl
# Patch /etc/issue
/bin/sed -i -e "s+$PREVIOUSVERSION+$UPGRADEVERSION+" /etc/issue

# Update menu
/usr/local/bin/updatemenu.pl

msg "$UPGRADEVERSION update installed."
