#!/bin/bash
#
# Upgrade IPCop
#

UPGRADEVERSION=1.9.15
PREVIOUSVERSION=1.9.14


msg() {
    /usr/bin/logger -t installpackage "$*"
    /bin/echo "$*"
}


# Verify architecture
MACHINE=`/usr/bin/perl -e "require '/usr/lib/ipcop/general-functions.pl';print \\$General::machine;"`
if [ "$MACHINE" != `/bin/cat ./ARCH` ]; then
    msg "Update for wrong architecture: `/bin/cat ./ARCH`! We are: $MACHINE. Aborting installation."
    exit 1
fi

# Verify version, note we also accept replaying an upgrade
CURRENTVERSION=`/usr/bin/perl -e "require '/usr/lib/ipcop/general-functions.pl';print \\$General::version;"`
if [ "$CURRENTVERSION" != "$PREVIOUSVERSION" -a "$CURRENTVERSION" != "$UPGRADEVERSION" ]; then
    msg "IPCop v$PREVIOUSVERSION or v$UPGRADEVERSION not running. Aborting installation."
    exit 1
fi

#####
#
# Add version specific handling *before* unpacking the patch here.
# For example stopping apache, squid, etc...
#
#####



#####
#
# End of version specific handling. Continue with universal stuff.
#
#####

FAILURE=0
/bin/tar -zxpf patch.tar.gz -C /
FAILURE=$?
if [ $FAILURE -ne 0 ]; then
    msg "Error extracting patch.tar.gz $1, need more free space on disk. Aborting."
    exit 4 # ERRORTAR
fi

# Modify or remove line below, depending on update
# Update bootloader config
# /usr/local/sbin/updatekernel.pl --add 2.6.27-2 --keep 2.6.27-1 --remove 2.6.27-0

# Modify or remove line below, depending on update
# Create the new initramfs
# /sbin/mkinitramfs --with-kernel=2.6.27-2 --with-firmware --many-modules --with-list=/etc/modules.initramfs

# Adjust the changed config files
# /usr/local/bin/upgrade.sh

# Remove old libraries (version specific)
/bin/rm -f /usr/lib/libcairo.so.2.10800.8
/bin/rm -f /usr/lib/libfreetype.so.6.3.22
/bin/rm -f /usr/lib/libfontconfig.so.1.4.1
/bin/rm -f /usr/lib/libglib-2.0.so.0.2100.0
/bin/rm -f /usr/lib/libgmodule-2.0.so.0.2100.0
/bin/rm -f /usr/lib/libgobject-2.0.so.0.2100.0
/bin/rm -f /usr/lib/libpango-1.0.so.0.2400.5
/bin/rm -f /usr/lib/libpangocairo-1.0.so.0.2400.5
/bin/rm -f /usr/lib/libpangoft2-1.0.so.0.2400.5
/bin/rm -f /usr/lib/libpixman-1.so.0.16.2

# For new shared libs. May not always be required, but makes sure we do not forget
/sbin/ldconfig

#####
#
# Add version specific handling *after* unpacking the patch here.
# For example restarting apache, squid, etc...
#
#####

# We don't need the rrdtool wrapper
/bin/rm -f /usr/lib/perl5/site_perl/5.10.1/RRDp.pm

# Modified and now .sh
/bin/rm -f /usr/local/bin/disk-partition

# Add ocspcerts directory to suppress logmessage
/bin/mkdir -p /etc/ipsec.d/ocspcerts

# restart squid (helper checks whether squid is enabled)
/usr/local/bin/restartsquid

#####
#
# End of version specific handling. Continue with universal stuff.
#
#####

# Patch general-functions.pl
/bin/sed -i -e "s+^\(\$General::version\s*=\s*\).*+\1'$UPGRADEVERSION';+" /usr/lib/ipcop/general-functions.pl
# Patch /etc/issue
/bin/sed -i -e "s+$PREVIOUSVERSION+$UPGRADEVERSION+" /etc/issue

# Update menu
/usr/local/bin/updatemenu.pl

msg "$UPGRADEVERSION update installed."
